wget -q -N -P /opt/DartDownload http://storage.googleapis.com/dart-archive/channels/stable/release/latest/editor/darteditor-windows-x64.zip
wget -q -N -P /opt/DartDownload http://storage.googleapis.com/dart-archive/channels/stable/release/latest/editor/darteditor-windows-ia32.zip
wget -q -N -P /opt/DartDownload http://storage.googleapis.com/dart-archive/channels/stable/release/latest/editor/darteditor-macos-x64.zip
wget -q -N -P /opt/DartDownload http://storage.googleapis.com/dart-archive/channels/stable/release/latest/editor/darteditor-linux-x64.zip
wget -q -N -P /opt/DartDownload http://storage.googleapis.com/dart-archive/channels/stable/release/latest/editor/darteditor-linux-ia32.zip
wget -q -N -P /opt/DartDownload http://storage.googleapis.com/dart-archive/channels/stable/release/latest/api-docs/dart-api-docs.zip
wget -q -N -P /opt/DartDownload http://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-macos-x64-release.zip
wget -q -N -P /opt/DartDownload http://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-ia32-release.zip
wget -q -N -P /opt/DartDownload http://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-x64-release.zip
wget -q -N -P /opt/DartDownload http://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-windows-ia32-release.zip
wget -q -N -P /opt/DartDownload http://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-windows-x64-release.zip  
